apiVersion: apps/v1
kind: Deployment
metadata:
  name: depp3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: depp3
  template:
    metadata:
      labels:
        app: depp3
    spec:
      containers:
      - name: depp3
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: depp3-service
spec:
  selector:
    app: depp3
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
